branches:
  only:
    - master

os:
- Visual Studio 2017
- Visual Studio 2015

platform: x64
configuration: Release

clone_folder: c:\projects\manif

build:
  project: c:\projects\manif\build\manif.sln

install:
  # Eigen 3.3-beta1
  - ps: wget -O eigen3.zip http://bitbucket.org/eigen/eigen/get/3.3-beta1.zip
  - cmd: 7z x eigen3.zip -o"C:\projects" -y > nul
  # - cmd: $env:CMAKE_INCLUDE_PATH = "C:\projects\eigen-eigen-ce5a455b34c0;$env:CMAKE_INCLUDE_PATH"
  #
  # Gtest
  - set ORIGIN_PATH=%cd%
  - set PATH=%PATH%;c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
  - git submodule update --init --recursive
  - cd ..
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake -G "Visual Studio 14 2015" .
  - devenv.exe googletest\msvc\gtest-md.sln /Upgrade
  - devenv.exe googletest\msvc\gtest-md.sln /Build
  - mkdir googletest\lib
  - copy googletest\msvc\gtest-md\Debug\gtestd.lib googletest\lib\gtest.lib
  - copy googletest\msvc\gtest-md\Debug\gtest_main-mdd.lib googletest\lib\gtest_main.lib
  - set GTEST_ROOT=%cd%\googletest
  - cd %ORIGIN_PATH%

build_script:
  - cd c:\projects\manif
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -D EIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-ce5a455b34c0 -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON ..
  - cmake --build .

after_build:
  - ctest

notifications:
  - provider: Email
    to:
      - deray.jeremie@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
